DROP TABLE PERSON;

DROP SEQUENCE SEQUENCE_FT_PESO;

DROP TRIGGER TRIGGER_FT_PESO;

DROP FUNCTION IMC;

 

CREATE TABLE PERSON(

ID NUMBER (5) CONSTRAINT pk_ID PRIMARY KEY,

FULL_NAME VARCHAR(50) NOT NULL,

PESO NUMBER(5,2),

ALTURA NUMBER(5,2)

);

 

CREATE SEQUENCE SEQUENCE_FT_PESO MINVALUE 50

MAXVALUE 100 INCREMENT BY 1;

 

 

create trigger "TRIGGER_FT_PESO" before insert on "PERSON"

for each row

begin

select SEQUENCE_FT_PESO.nextval into:new.PESO

from dual;

end;

 

CREATE FUNCTION IMC (PESO IN NUMBER, ALTURA IN NUMBER) RETURN NUMBER IS

BEGIN

    RETURN (PESO/(ALTURA*ALTURA));

END IMC;

 

INSERT INTO "PERSON" (ID, FULL_NAME, ALTURA) VALUES (1, 'JORGE', 1.76);

INSERT INTO "PERSON" (ID, FULL_NAME, ALTURA) VALUES (2, 'JOÃO', 1.50);

INSERT INTO "PERSON" (ID, FULL_NAME, ALTURA) VALUES (3, 'GEFERSON', 1.90);

INSERT INTO "PERSON" (ID, FULL_NAME, ALTURA) VALUES (4, 'EDUARDO', 2.10);

 

SELECT * FROM PERSON;

SELECT ROUND(IMC(PESO, ALTURA)) FROM PERSON;
